[package]
edition = "2018"
name = "chip8-emulator"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9"
lazy_static = "1.4.0"
log = "0.4"
rand = "0.8.0"
sdl2 = "0.34"
